<?php if (isset($name)) { ?>
Dear <?=$name?><br />
<br />
<?php } ?>
You have requested to have your password reset for your account.<br />
<br />
Please visit this url to reset your password.<br />
<br />
<a href="<?=$this->url('e4w/zfc-user-forgot-password/change-password', ['token' => $token], ['force_canonical' => true])?>"><?=$this->url('e4w/zfc-user-forgot-password/change-password', ['token' => $token], ['force_canonical' => true])?></a><br />
<br />
If you received this email in error, you can safely ignore this email.
