<?php
/** @var \Eye4web\ZfcUser\ForgotPassword\Form\Forgot\ChangePasswordForm $form */
$form = $this->form;

echo $this->form()->openTag($form);
echo $this->formRow($form->get('new_password')) . '<br />';
echo $this->formRow($form->get('confirm_new_password')) . '<br />';
echo $this->formRow($form->get('submit')->setLabel('Save'));
echo $this->formRow($form->get('csrf'));
echo $this->form()->closeTag($form);